baseURL = "https://chipverif.github.io/"
languageCode = "en-us"
title = "Chipverif Open Source"
theme = "ananke"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "High-quality CoCoTB verification IP and open source projects"
  github = "https://github.com/chipverif"